#Reusabel Build Set Up Workflow
name: Build SetUp (Shared)

on:
  workflow_call:

jobs:
  SetUp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Checkout first to ensure go.sum is available
    - uses: actions/setup-python@v4 # Setup Python
      with:
        python-version: '3.10'
        
    - uses: actions/setup-go@v4  # Setup Go after checkout
      with:
        go-version: '1.18'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install plugin
      run: |
        pip install pytest pytest-cov
    outputs:
        pytest_installed: ${{ steps.intall_plugin.outputs.exit_code == 0 }}
