#Reusable Build Set Up Workflow
name: Build SetUp (Shared)

on:
  workflow_call:

jobs:
  SetUp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Checkout first to ensure go.sum is available
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Set Up Go
      uses: actions/setup-go@v4  # Setup Go after checkout
      with:
        go-version: '1.21.3'
