#Trigger when there is a push
name: Continuous Integration
on:
  push:
  
jobs:
  # Set up necessary installs
  Test_TDD:
    name: Build Set Up and Test TDD
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        cache-dependency-path: subdir/go.sum

    - name: Checkout Development Repository
      uses: actions/checkout@v4
      
    - name: Install Dependencies
      run: |
        go mod download

    #CI Workflow Fail
    - name: Create Issue for Failed Workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: "${{ github.workflow }} Failed"
        assignees: lacsadoshaniahsantiago, koayyiting

    - name: Workflow Fail Discord
      if: ${{ failure() }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          username: Mr CI
          color: '#ff00aa'
          description: ${{ github.workflow }} failed.
          details: 'Please review workflow and make changes!'
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_URL }}

    # TDD Test
    - uses: actions/checkout@v4
    - name: Run TDD Test
      uses: robherley/go-test-action@v0.1.0

    # Create Issue on Fail TDD Tests
    - name: Create Issue on TDD Test Failure
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: "Unit Testing Failings in ${{ github.workflow }} "
        body: |
          **Failed tests have been detected.**
          [Test Results Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          **Please investigate and address the failures.**
        assignees: ${{ github.actor }}

    - name: TDD Error Discord
      if: ${{ failure() }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: error
          details: Go Unit Tests Fails
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_URL }}
          
  Test_BDD:
    name: Testing BDD
    needs: Test_TDD
    if: ${{ success() }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: koayyiting/mysql_test:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: can_we_still_score_for_dop
    steps:
    # Build and Run MySQL Container and Detach
    - name: Start MySQL Container
      run: docker run --name mysql_container -d koayyiting/mysql_test:latest

    # Test DB if Working
    - name: Wait MySQL To Start
      run: |
        sleep 10
        
        docker exec mysql_container sh -c 'mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "SHOW DATABASES;"'
        docker exec mysql_container sh -c 'mysql -u root -p"${MYSQL_ROOT_PASSWORD}" -e "USE record_db; SHOW TABLES;"'

    - name: Checkout Testing Repository
      uses: actions/checkout@v2
      with:
        repository: DevOpsTeamB2023/DevOps_Oct2023_TeamB_Testing

    # BDD Test
    - name: Run BDD tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: TestCases

   # Create Issue on Fail BDD Tests
    - name: Create Issue on BDD Test Failure
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: "BDD Fail Tests in ${{ github.workflow }} "
        body: |
          **Failed tests have been detected.**
          [Test Results Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          **Please investigate and address the failures.**
        assignees: luketeran, ${{ github.actor }}

    #Notify Discord Channel
    - name: BDD Error Discord
      if: ${{ failure() }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: error
          details: Behaviour Tests Fail
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_URL }}

    - name: Successful Tests Discord 
      if: ${{ success() }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          color: '#ff00aa'
          username: Mr CI
          description: All Tests Passed in ${{ github.workflow }} Workflow from ${{ github.ref_name }}
          details: '(https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
          footer: By ${{ github.actor }}
          webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK_URL }}

    # Display BDD Report in Github Action
    - name: Upload BDD Test Report
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports

    - uses: actions/checkout@v4
    - name: Download BDD Test Report
      if: always()
      uses: actions/download-artifact@v1
      with:
        name: reports

    - name: Send BDD Report to Commit
      if: always()
      uses: joonvena/robotframework-reporter-action@v2.3
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
