#Release/Deployment
name: Release/Deployment  
on:
  push:
  #workflow_run:
    #workflows:
      #- "PullRequest"
    #types:
      #- completed

jobs:
  # Set up necessary installs
  Build_SetUp_and_TDD:
    name: Build SetUp
    runs-on: ubuntu-latest
    services:
      mysql:
        image: koayyiting/mysql_test:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: can_we_still_score_for_dop
    steps:
    - name: Set Up Go
      uses: actions/setup-go@v5  # Setup Go after checkout
      with:
        go-version: '1.21.x'
        cache-dependency-path: subdir/go.sum

  #Testing
    
  #Create Git Release
  Create_Git_Release:
    needs: Build_SetUp_and_TDD
    name: Create Git Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Version
        id: get-version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Increment Version
        id: increment-version
        run: echo "::set-output name=version::$((${{ steps.get-version.outputs.version }} + 1))"

      - name: Update Version File
        run: echo "${{ steps.increment-version.outputs.version }}" > version.txt

      - name: Create a release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment-version.outputs.version }}
          release_name: Release v${{ steps.increment-version.outputs.version }}
